version: "3.9"

services:
  composeapp:
    build: ../../composeApp/build/dist/wasmJs/productionExecutable
    container_name: composeapp-wasm
    ports:
      - "9000:80"
    restart: unless-stopped
